### PR TITLE
encoding: document message encoding

### PR DESCRIPTION
**Pull request by naure**

### CODE REVIEW

**Review by svalasovich — APPROVED** [review]

**Review by svalasovich — APPROVED** [review]
I think it's hard to assess the usefulness of this feature at the current stage. I think it will have reason if we are going to support many serialization formats (proto, avro, thrift, JSON etc.)

**Comment by naure** [comment]
We have three formats in use:
* JSON for convenience and readability.
* Protobuf for efficiency.
* SCALE for maximum efficiency in smart contracts.

The thing is that it is hard to add it later after SDKs are released and data exists permanently in mainnet. It’s still easy to upgrade HTTP APIs but not smart contracts and storage data.

**Comment by naure** [comment]
I added notes about JSON, ProtoBuf, and SCALE, and a clearer motivation.

**Comment by svalasovich** [comment]
Deprecated

**Pull request closed without merging**
